# OrangePi 6 Plus : exposer DP + HDMI (cix_sky1) via le profil Pro Audio
device.profile.priority.rules = [
  {
    matches = [
      { device.name = "alsa_card.platform-sound" }
    ]
    actions = {
      update-props = {
        priorities = [ "pro-audio" ]
      }
    }
  }
]
