# OrangePi 6 Plus : quantum 4096 tant que le sink DP/HDMI est actif (xruns à 1024) + noms lisibles
monitor.alsa.rules = [
  {
    matches = [ { node.name = "alsa_output.platform-sound.pro-output-1" } ]
    actions = {
      update-props = {
        node.description    = "HDMI"
        node.nick           = "HDMI"
        node.force-quantum  = 4096
      }
    }
  }
  {
    matches = [ { node.name = "alsa_output.platform-sound.pro-output-0" } ]
    actions = {
      update-props = {
        node.description    = "DisplayPort"
        node.nick           = "DisplayPort"
        node.force-quantum  = 4096
      }
    }
  }
]
